<?php

namespace Database\Seeders;

use App\Enums\ItemRarity;
use App\Enums\ItemType;
use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // === Offensive (14) ===
            [
                'slug' => 'splatter_bomb',
                'name' => 'Splatter Bomb',
                'description' => "Reduce target's step count by 5% for today",
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Common,
                'effect' => ['type' => 'reduce_steps', 'value' => 5, 'unit' => 'percent'],
                'icon' => '💣',
                'is_public' => true,
            ],
            [
                'slug' => 'toilet_paper_trail',
                'name' => 'Toilet Paper Trail',
                'description' => "Expose target's steps to everyone in the league",
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Common,
                'effect' => ['type' => 'expose_steps'],
                'icon' => '🧻',
                'is_public' => true,
            ],
            [
                'slug' => 'skid_mark',
                'name' => 'Skid Mark',
                'description' => "Silently reduce target's steps by 3%",
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Common,
                'effect' => ['type' => 'reduce_steps', 'value' => 3, 'unit' => 'percent'],
                'icon' => '👣',
                'is_public' => true,
            ],
            [
                'slug' => 'stink_cloud',
                'name' => 'Stink Cloud',
                'description' => 'Reduce all other league members steps by 2%',
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Uncommon,
                'effect' => ['type' => 'reduce_steps', 'value' => 2, 'unit' => 'percent'],
                'icon' => '☁️',
                'is_public' => true,
            ],
            [
                'slug' => 'clogged_pipes',
                'name' => 'Clogged Pipes',
                'description' => 'Block target from using items today',
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Uncommon,
                'effect' => ['type' => 'block_items'],
                'icon' => '🪠',
                'is_public' => true,
            ],
            [
                'slug' => 'the_brown_out',
                'name' => 'The Brown Out',
                'description' => "Hide target's ranking from them today",
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Uncommon,
                'effect' => ['type' => 'hide_ranking'],
                'icon' => '🌑',
                'is_public' => true,
            ],
            [
                'slug' => 'courtesy_flush',
                'name' => 'Courtesy Flush',
                'description' => "Remove all of target's active defenses",
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Rare,
                'effect' => ['type' => 'remove_defense'],
                'icon' => '🚿',
                'is_public' => true,
            ],
            [
                'slug' => 'sewer_backup',
                'name' => 'Sewer Backup',
                'description' => "Reverse target's active step boosts into reductions",
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Rare,
                'effect' => ['type' => 'reverse_buff'],
                'icon' => '🕳️',
                'is_public' => true,
            ],
            [
                'slug' => 'diarrhea_attack',
                'name' => 'Diarrhea Attack',
                'description' => "Steal 8% of target's steps",
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Rare,
                'effect' => ['type' => 'steal_steps', 'value' => 8, 'unit' => 'percent'],
                'icon' => '💩',
                'is_public' => true,
            ],
            [
                'slug' => 'porta_potty_trap',
                'name' => 'Porta-Potty Trap',
                'description' => "Set a trap — target's next item use fails and costs -5% steps",
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Rare,
                'effect' => ['type' => 'set_trap', 'penalty' => 5],
                'icon' => '🚽',
                'is_public' => true,
            ],
            [
                'slug' => 'upper_decker',
                'name' => 'Upper Decker',
                'description' => 'Swap your final placement with the target at midnight',
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Epic,
                'effect' => ['type' => 'swap_placement'],
                'icon' => '🪤',
                'is_public' => true,
            ],
            [
                'slug' => 'explosive_diarrhea',
                'name' => 'Explosive Diarrhea',
                'description' => "Reduce target's steps by 10% with 5% splash on a nearby player",
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Epic,
                'effect' => ['type' => 'reduce_steps', 'value' => 10, 'unit' => 'percent', 'splash' => 5],
                'icon' => '🌋',
                'is_public' => true,
            ],
            [
                'slug' => 'poop_streak',
                'name' => 'Poop Streak',
                'description' => 'If target finishes last, their losing streak doubles',
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Epic,
                'effect' => ['type' => 'double_streak'],
                'icon' => '📈',
                'is_public' => true,
            ],
            [
                'slug' => 'septic_tank',
                'name' => 'Septic Tank',
                'description' => 'The more steps target takes, the bigger the reduction (-1% per 1k, max -15%)',
                'type' => ItemType::Offensive,
                'rarity' => ItemRarity::Legendary,
                'effect' => ['type' => 'scaling_reduction', 'per' => 1000, 'max' => 15],
                'icon' => '🛢️',
                'is_public' => true,
            ],

            // === Defensive (9) ===
            [
                'slug' => 'plunger',
                'name' => 'Plunger',
                'description' => 'Remove one active negative effect',
                'type' => ItemType::Defensive,
                'rarity' => ItemRarity::Common,
                'effect' => ['type' => 'remove_effect'],
                'icon' => '🪠',
                'is_public' => true,
            ],
            [
                'slug' => 'wet_wipe',
                'name' => 'Wet Wipe',
                'description' => "Reduce an active negative effect's damage by 50%",
                'type' => ItemType::Defensive,
                'rarity' => ItemRarity::Uncommon,
                'effect' => ['type' => 'reduce_damage'],
                'icon' => '🧻',
                'is_public' => false,
            ],
            [
                'slug' => 'odor_shield',
                'name' => 'Odor Shield',
                'description' => 'Remove an active negative effect and hide your steps from the attacker',
                'type' => ItemType::Defensive,
                'rarity' => ItemRarity::Uncommon,
                'effect' => ['type' => 'hide_steps_from_attacker'],
                'icon' => '🛡️',
                'is_public' => false,
            ],
            [
                'slug' => 'bidet_shield',
                'name' => 'Bidet Shield',
                'description' => 'Reflect an active negative effect back to the attacker',
                'type' => ItemType::Defensive,
                'rarity' => ItemRarity::Rare,
                'effect' => ['type' => 'reflect_attack'],
                'icon' => '🔄',
                'is_public' => false,
            ],
            [
                'slug' => 'decoy_dump',
                'name' => 'Decoy Dump',
                'description' => '50% chance to cancel an active negative effect',
                'type' => ItemType::Defensive,
                'rarity' => ItemRarity::Rare,
                'effect' => ['type' => 'dodge'],
                'icon' => '🎯',
                'is_public' => false,
            ],
            [
                'slug' => 'hazmat_suit',
                'name' => 'Hazmat Suit',
                'description' => 'Remove all active negative effects',
                'type' => ItemType::Defensive,
                'rarity' => ItemRarity::Epic,
                'effect' => ['type' => 'block_all_attacks'],
                'icon' => '🦺',
                'is_public' => false,
            ],
            [
                'slug' => 'probiotic_shield',
                'name' => 'Probiotic Shield',
                'description' => 'Remove an active negative effect and gain +2% step boost',
                'type' => ItemType::Defensive,
                'rarity' => ItemRarity::Epic,
                'effect' => ['type' => 'reactive_bonus', 'value' => 2, 'unit' => 'percent'],
                'icon' => '💊',
                'is_public' => false,
            ],
            [
                'slug' => 'golden_throne',
                'name' => 'Golden Throne',
                'description' => 'Negate an active negative effect and gain +3% step boost',
                'type' => ItemType::Defensive,
                'rarity' => ItemRarity::Legendary,
                'effect' => ['type' => 'negate_and_bonus', 'value' => 3, 'unit' => 'percent'],
                'icon' => '👑',
                'is_public' => false,
            ],
            [
                'slug' => 'titanium_toilet',
                'name' => 'Titanium Toilet',
                'description' => 'Remove all active negative effects and gain +3% step boost',
                'type' => ItemType::Defensive,
                'rarity' => ItemRarity::Legendary,
                'effect' => ['type' => 'block_all_and_bonus', 'value' => 3, 'unit' => 'percent'],
                'icon' => '🏆',
                'is_public' => false,
            ],

            // === Strategic (14) ===
            [
                'slug' => 'scouts_scope',
                'name' => "Scout's Scope",
                'description' => "See one player's current step count",
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Common,
                'effect' => ['type' => 'spy_single'],
                'icon' => '🔭',
                'is_public' => true,
            ],
            [
                'slug' => 'fiber_boost',
                'name' => 'Fiber Boost',
                'description' => 'Add 5% bonus to your steps at midnight',
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Common,
                'effect' => ['type' => 'boost_steps', 'value' => 5, 'unit' => 'percent'],
                'icon' => '🥦',
                'is_public' => true,
            ],
            [
                'slug' => 'morning_coffee',
                'name' => 'Morning Coffee',
                'description' => 'Get a 10% bonus on all steps taken before noon',
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Common,
                'effect' => ['type' => 'timed_boost', 'multiplier' => 1.1, 'before_hour' => 12],
                'icon' => '☕',
                'is_public' => true,
            ],
            [
                'slug' => 'peek_a_poo',
                'name' => 'Peek-a-Poo',
                'description' => 'See your current position in today\'s standings',
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Common,
                'effect' => ['type' => 'spy_self_rank'],
                'icon' => '👀',
                'is_public' => true,
            ],
            [
                'slug' => 'fake_poop',
                'name' => 'Fake Poop',
                'description' => 'Show a fake step count to other players today',
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Uncommon,
                'effect' => ['type' => 'fake_steps', 'variance' => 30],
                'icon' => '🎭',
                'is_public' => false,
            ],
            [
                'slug' => 'laxative',
                'name' => 'Laxative',
                'description' => "Reveal target's current steps to the entire league",
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Uncommon,
                'effect' => ['type' => 'force_reveal'],
                'icon' => '💊',
                'is_public' => true,
            ],
            [
                'slug' => 'copycat',
                'name' => 'Copycat',
                'description' => 'Copy the most recently used item effect in the league',
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Rare,
                'effect' => ['type' => 'copy_item'],
                'icon' => '🐱',
                'is_public' => true,
            ],
            [
                'slug' => 'anonymous_tip',
                'name' => 'Anonymous Tip',
                'description' => 'Your identity is hidden when using items today',
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Rare,
                'effect' => ['type' => 'anonymous_mode'],
                'icon' => '🕶️',
                'is_public' => false,
            ],
            [
                'slug' => 'the_insider',
                'name' => 'The Insider',
                'description' => "See everyone's inventory in the league",
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Rare,
                'effect' => ['type' => 'spy_inventory'],
                'icon' => '🕵️',
                'is_public' => true,
            ],
            [
                'slug' => 'double_or_nothing',
                'name' => 'Double or Nothing',
                'description' => 'Coin flip at midnight: +10% or -10% steps',
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Epic,
                'effect' => ['type' => 'coin_flip', 'win' => 10, 'lose' => 10],
                'icon' => '🎰',
                'is_public' => true,
            ],
            [
                'slug' => 'prune_juice',
                'name' => 'Prune Juice',
                'description' => 'Force target to use their rarest item on a random player',
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Epic,
                'effect' => ['type' => 'force_use'],
                'icon' => '🧃',
                'is_public' => true,
            ],
            [
                'slug' => 'crystal_ball',
                'name' => 'Crystal Ball',
                'description' => 'See projected end-of-day standings based on current pace',
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Epic,
                'effect' => ['type' => 'projection'],
                'icon' => '🔮',
                'is_public' => true,
            ],
            [
                'slug' => 'toilet_swap',
                'name' => 'Toilet Swap',
                'description' => "Steal a random item from target's inventory",
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Legendary,
                'effect' => ['type' => 'steal_item'],
                'icon' => '🔀',
                'is_public' => true,
            ],
            [
                'slug' => 'royal_flush',
                'name' => 'Royal Flush',
                'description' => 'Swap 1st and last place positions at midnight',
                'type' => ItemType::Strategic,
                'rarity' => ItemRarity::Legendary,
                'effect' => ['type' => 'swap_first_last'],
                'icon' => '🃏',
                'is_public' => true,
            ],
        ];

        foreach ($items as $item) {
            Item::query()->updateOrCreate(
                ['slug' => $item['slug']],
                $item,
            );
        }
    }
}
